### ISSUE TITLE
[Blog Page] Al comentar no se muestra la info del Input website

### ISSUE THREAD

**Issue by nacho87** [insignia4u/i4u#184]
Al comentar y llenar los datos. como ser el nombre, email , website y comentario. 

Luego al mostrar el comentario que se envió no muestra el dato de Website. 
Se muestra nombre o anónimo si no se puso nada y el comentario. 
Es correcto que se muestra ademas si lo ingreso al Website.

**Comment by ckozus** [comment]
El campo website quedó fuera de los comentarios.
