### ISSUE TITLE
[General] Archivo css faltante

### ISSUE THREAD

**Issue by nacho87** [insignia4u/i4u#188]
Al Ingresar en Home pide un archivo .css que lo indica como que no se encuentra.

GET http://i4u-staging.herokuapp.com/assets/jquery.reject.css 404 (Not Found)

**Comment by ckozus** [comment]
reject.js es usado para mostrar un mensaje cuando la versión del browser (IE en particular) es muy vieja. Habría que incluirlo porque no está siendo encontrado.

Reject está siendo llamado en i4u.cofee.js y está siendo requerido correctamente en el application.js, pero aparentemente no se está detectando la ruta donde el archivo está ubicado.

**Comment by marianaloran** [comment]
En producción
