### ISSUE TITLE
Añadir en el TITLE una variable para las diferentes paginas del sitio y articulos del blog

### ISSUE THREAD

**Issue by diegopaz** [insignia4u/i4u#199]
Cada una de las páginas debe tener personalizado el elemento title.

Principalmente las secciones principales y cada uno de los proyectos del portfolio.

Los artículos del blog ya tienen title personalizados, pero no lo tiene la página principal del blog: /blog

**Comment by marianaloran** [comment]
@ckozus También en staging.

**Comment by ckozus** [comment]
@marianaloran fijate que en la página de proyectos no está funcionando el title, para este no muestra nada por ejemplo:

http://i4u-staging.herokuapp.com/projects/los-tanfaun

**Comment by marianaloran** [comment]
Listo!

**Comment by ckozus** [comment]
@marianaloran Pasemos a producción entonces! :)


On Thu, Oct 15, 2015 at 9:08 AM, marianaloran <notifications@github.com>
wrote:

> Listo!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/insignia4u/i4u/issues/199#issuecomment-148367591>.
>



-- 
http://ar.linkedin.com/in/carloskozuszko
http://www.insignia4u.com

**Comment by marianaloran** [comment]
En producción
