### ISSUE TITLE
Implementar Feature Box en el blog

### ISSUE THREAD

**Issue by ckozus** [insignia4u/i4u#246]
Nicolás ya tiene trabajo en progreso para esta sección. Falta adaptar el diseño que hizo a mobile e integrar la suscripcion al newsletter (se puede utilizar lo mismo que se está utilizando en el footer actualmente para suscribir a usuarios).

**Comment by ckozus** [comment]
@nicocedron por favor pasale a @marianaloran los avances que vos ya vas haciendo así ella los termine. Gracias!

**Comment by nicocedron** [comment]
@marianaloran Ya esta subida la rama, se llama [blog-new-header]

**Comment by marianaloran** [comment]
Ok gracias!

**Comment by ckozus** [comment]
Hola @marianaloran,

Estuvimos hablando con Juan y esa sección en realidad debería tener el mismo estilo (tipografías, colores, etc) que el footer, donde actualmente se encuentra la suscripción al newsletter.

Y en el blog, quitar la suscripción al newsletter porque sería redundante.

Funciona la suscripción? Porque actualmente pongo un mail y veo que se vuelve a recargar la página nomás. La idea es que usando las credenciales de MailChimp de Insignia, se suscriba al usuario a la lista de correo llamada "Tucuman".

**Comment by marianaloran** [comment]
@ckozus Los cambios están en staging.

**Comment by ckozus** [comment]
Hola @marianaloran,

Te adjunto una captura para pedirte algunos cambios:

![screen shot 2015-10-14 at 10 01 52 am](https://cloud.githubusercontent.com/assets/12102/10484321/dfbb6e10-725a-11e5-8e80-7bd8b9cfdfe2.png)

Con Juan probamos quitando la linea azul separadora que está marcada y vimos que queda mejor si no la incluimos.

También queda mejor si sacamos la palabra "Newsletter" y queda centrado lo otro.

Hay mucho espacio entre el final del header y el comienzo del blog.

También, cuando veo la página desde una tablet, veo repetidas las secciones de Tips, aparecen antes y después del artículo.

**Comment by marianaloran** [comment]
Listo estos cambios

**Comment by ckozus** [comment]
@marianaloran Pasemos a producción.

On Thu, Oct 15, 2015 at 9:08 AM, marianaloran <notifications@github.com>
wrote:

> Listo estos cambios
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/insignia4u/i4u/issues/246#issuecomment-148367543>.
>



-- 
http://ar.linkedin.com/in/carloskozuszko
http://www.insignia4u.com

**Comment by marianaloran** [comment]
En producción
