### ISSUE TITLE
Calendar - Admin del Blog

### ISSUE THREAD

**Issue by mfernanda** [insignia4u/i4u#247]
Cuando se escribe algo mal en el calendario (por ejemplo: el mes superior a 12) se guarda el articulo normalmente, pero en la pagina del blog de insignia da ERROR 500.
Esto no debería suceder, sino q deberia notificar del error directamente en el admin.

**Comment by ckozus** [comment]
Yo opino que en el render directamente se visualice un mensaje de error en vez del calendario, por ejemplo "Fecha incorrecta", para que el que está editando el artículo pueda verlo y corregirlo.

Me parece que es más facil modificar el helper que hace el output y listo.

**Comment by ckozus** [comment]
Aquí adjunto el error:

http://insignia-errbit.herokuapp.com/apps/50b4f75a6f9cb90005000008/problems/55f6ed79312d1f0009000116

Ver credenciales para acceder a errbit en Trello.

**Comment by marianaloran** [comment]
En producción.
