### ISSUE TITLE
Artículos del blog - Clases y horas (new feature)

### ISSUE THREAD

**Issue by mfernanda** [insignia4u/i4u#248]
Esto mismo, con este mismo formato, debería aparecer en los artículos de capacitación en el blog:

![image](https://cloud.githubusercontent.com/assets/4872397/9880669/f1e3719c-5ba2-11e5-98cd-ce4117e99b86.png)

Uno debería cargar esos datos al escribir el artículo y si están cargados, solo debería mostrar ese recuadro así resaltado.

O por ahi con un marcador tipo el {{calendar}}

{{training 6 2 3 $650 10%}}

**Comment by ckozus** [comment]
@mfernanda Le pedí a @marianaloran que este componente sea responsive, que una de las columnas pase abajo cuando se vea la sección mobile.

**Comment by matiasmoya** [comment]
@ckozus @mfernanda yo opino que en lugar de hacerle descargar fuentes al usuario, y jugarse con que en algun dispositivo/browser esto no funcione.. es mejor preparar la imagen, que no varia tanto y pueden tener varias preparadas. 
IMHO

**Comment by ckozus** [comment]
Bueno, estoy abierto a que usemos una fuente estándar nomás, creo que no es
una parte tan importante del requerimiento. A mi me interesa que se genere
el bloque destacado con esa información.

Si queremos cambiar la tipografía, cambiemos nomás.


2015-10-02 10:54 GMT-03:00 matiasmoya <notifications@github.com>:

> @ckozus <https://github.com/ckozus> @mfernanda
> <https://github.com/mfernanda> yo opino que en lugar de hacerle descargar
> fuentes al usuario, y jugarse con que en algun dispositivo/browser esto no
> funcione.. es mejor preparar la imagen, que no varia tanto y pueden tener
> varias preparadas.
> IMHO
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/insignia4u/i4u/issues/248#issuecomment-145028469>.
>



-- 
http://ar.linkedin.com/in/carloskozuszko
http://www.insignia4u.com

**Comment by matiasmoya** [comment]
@ckozus perdon, recien me fijo :P y Enriqueta la tenemos cargada hace rato en el head

**Comment by matiasmoya** [comment]
![](http://www.thehindu.com/multimedia/dynamic/02273/10kimp_jetpack_tif_2273739g.jpg)

**Comment by ckozus** [comment]
@matiasmoya Mi próxima hija se va a llamar Enriqueta.

2015-10-02 10:57 GMT-03:00 matiasmoya <notifications@github.com>:

> @ckozus <https://github.com/ckozus> perdon, recien me fijo :P y Enriqueta
> la tenemos cargada hace rato en el head
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/insignia4u/i4u/issues/248#issuecomment-145029060>.
>



-- 
http://ar.linkedin.com/in/carloskozuszko
http://www.insignia4u.com

**Comment by marianaloran** [comment]
{{training '# classes' '# hours' '# weeks' '$ price' '% discount' }}
Se entiende para agregar en el hint?

**Comment by ckozus** [comment]
{{training clases horas weeks price discount% }}

y agregar el ejemplo para que no quede lugar a dudas:

{{training 3 2 6 1000 10%}}



On Fri, Oct 2, 2015 at 11:01 AM, marianaloran <notifications@github.com>
wrote:

> {{training '# classes' '# hours' '# weeks' '$ price' '% discount' }}
> Se entiende para agregar en el hint?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/insignia4u/i4u/issues/248#issuecomment-145029921>.
>



-- 
http://ar.linkedin.com/in/carloskozuszko
http://www.insignia4u.com
